.TL
Multi-Class Classification using Neural Networks
.AU
Mayank Kharbanda - Samyak Ahuja
.AI
University of Delhi

.AB
We have used the Forest Cover Type (covset) dataset for our multiclass
classification using Deep Neural Networks (DNN). The dataset is first
analysed by using Logistic Regression for multiclass data and Support
Vector Machines. The result is then compared with Neural Networks of
different configurations and hyperparameters.
.AE

.SH
Introduction

